# Generated by Django 3.2.7 on 2022-01-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(choices=[('PrivatBank', 'PrivatBank'), ('MonoBank', 'MonoBank')], default='PrivatBank', max_length=64),  # noqa
        ),
    ]
