# Generated by Django 3.2.7 on 2021-11-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='source',
            field=models.CharField(default='Unknown', max_length=25),
        ),
    ]
