# Generated by Django 3.2.7 on 2021-11-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_rate_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='message',
            field=models.TextField(default=1, max_length=1500),
            preserve_default=False,
        ),
    ]
