# Generated by Django 3.2.7 on 2021-11-27 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_contactus_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='type',
            new_name='cur_type',
        ),
    ]
