# Generated by Django 3.2.7 on 2021-11-27 19:40

from django.db import migrations, models
import django.utils.timezone  # noqa


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_rename_type_rate_cur_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
