# Generated by Django 3.2.7 on 2022-02-01 19:32

import currency.models

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='avatar',
            field=models.FileField(blank=True, default=None, null=True, upload_to=currency.models.upload_avatar),
        ),
    ]
