# Generated by Django 3.2.7 on 2021-12-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='cur_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Dollar'), (2, 'Euro')]),
        ),
    ]
