# Generated by Django 3.2.7 on 2022-02-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_auto_20220201_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='avatar',
            new_name='logo',
        ),
    ]
