# Generated by Django 3.2.7 on 2021-12-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_alter_rate_cur_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='cur_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Dollar'), (2, 'Euro')], default=1),
        ),
    ]
