# Generated by Django 3.2.7 on 2021-12-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_auto_20211212_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='raw_content',
            field=models.TextField(default=''),
        ),
    ]
