# Generated by Django 3.2.7 on 2021-12-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_alter_contactus_raw_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('request_method', models.CharField(choices=[
                    ('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=255)),
                ('response_time', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
